export { default as NavBar } from './NavBar';
export { default as Foot } from './Foot';
export { default as PageContent } from './PageContent';
export { default as HomePage1 } from './HomePage1';
export { default as HomePage2 } from './HomePage2';
export { default as HomePage3 } from './HomePage3';
export { default as HomePage4 } from './HomePage4';
export { default as HomePage5 } from './HomePage5';
export { default as ContactUs } from './ContactUs';
